// flow-typed signature: dafeb8b6549d55e11f2a6ae86ce8d9bf
// flow-typed version: <<STUB>>/compression_v1.7.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compression'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compression' {
  declare module.exports: any;
}
