// flow-typed signature: 89856003ec0f15b8b3a0fe6801933262
// flow-typed version: <<STUB>>/cors_v2.8.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cors' {
  declare module.exports: any;
}
