// flow-typed signature: 4b85f2282d5fcd4ca81daa10e3181e81
// flow-typed version: <<STUB>>/express_v4.16.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express' {
  declare module.exports: any;
}
