// flow-typed signature: c08985f38d5f43258ee0b1d6e74d5515
// flow-typed version: <<STUB>>/styled-components_v2.4.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}
